refactor: Добавить классы User и Film, UserController и FilmControlle…
ElenaSsV/java-filmorate pull request #10
Opened 2023-07-03 16:11 UTC by ElenaSsV

…r, test: добавить тесты

2023-07-04 08:16 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        validate(film);
По ТЗ нужно добавить логирование для операций, которые изменяют сущности — добавляют и обновляют их. Также причины ошибок — например, если валидация не пройдена		
Например здесь перед 23 строкой нужно вставить
log.info("Creating film {}", film);

2023-07-04 08:19 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private final Map<Integer, User> users = new HashMap<>();
Логика хранения объектов одинаковая у обоих контроллеров, поэтому можно было ее вынести в базовый контроллер-дженерик

2023-07-04 08:22 UTC, VadimZharkov commented on src/test/java/ru/yandex/practicum/filmorate/FilmValidationTest.java
> +                new Executable() {
Более читаемо если использовать лямбду
 ValidationException exception = assertThrows(ValidationException.class, () -> {
           //Code under test
  });

2023-07-07 07:54 UTC, ElenaSsV commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private final Map<Integer, User> users = new HashMap<>();
Я вынесла, но не совсем понятно, как тогда присваивать id при создании и получать id при обновлении. Плюс не получается присвоить логин в качестве имени пользователя при помощи аннотации, если имя пользователя не задано. Сделала отдельный метод.  Возможно вернуть как было?

2023-07-07 08:23 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/controller/Controller.java
> +    private long validateValue(T value) {
То что CRUD в базовый класс все верно, а вот валидация у каждого своя и реализовать нужно в наследниках.
Для этого можно 1. сделать базовый контроллер абстрактным с абстрактным методом long validateValue(T value).
или
2.  long validateValue(T value) сделать пустым и в наследниках переопределить
или
3.  сделать отдельный класс валидатор, сделать два поименованных спринговых бина с реализацией для Film и User, а в базовом контроллере поле для валидатора и параметр в конструкторе.

3 самый "кошерный" spring-way, но вы еще многого не проходили, 2 для ленивых, поэтому предлагаю реализовать 1 - ый

2023-07-07 08:28 UTC, VadimZharkov commented on src/test/java/ru/yandex/practicum/filmorate/UserControllerTest.java
> +    @SneakyThrows
А @SneakyThrows осознано используешь)? С пониманием что это?

2023-07-07 08:33 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private final Map<Integer, User> users = new HashMap<>();
как то так
	private final HashMap<Long, T> storage = new HashMap<>();
	private long counter = 0L;

	public T create(final T data) {
		validate(data);
		data.setId(++counter);
		storage.put(data.getId(), data);
		return data;
	}

2023-07-07 09:53 UTC, ElenaSsV commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private final Map<Integer, User> users = new HashMap<>();
Но ведь у T data нет геттеров и сеттеров

2023-07-07 10:34 UTC, ElenaSsV commented on src/test/java/ru/yandex/practicum/filmorate/UserControllerTest.java
> +    @SneakyThrows
Не совсем осознанно. Но увидела, что другие так делают) Лучше убрать?

2023-07-07 10:39 UTC, ElenaSsV commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        validate(film);
В теории было, что мы можем прописывать вручную или использовать LogBook. Я добавила  LogBook и выставила уровень trace. Либо предполагается, что при использовании LogBook все равно нужно добавлять log.info?

2023-07-08 09:03 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        validate(film);
нужно в любом случае, lombok это препроцессор, который может сделать некоторые вещи за программиста, например добавть в класс поле log. а вызвать метод чтобы в лог записалось должна ты

2023-07-08 09:15 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private final Map<Integer, User> users = new HashMap<>();
можно сделать базовый интерфейс например Entity и сказать что у него должен быть метод setId и getId
занаследовать от него Фильм и Юзера, а абстрактный базовый контроллер определить так

public abstract class Controller<T extends Entity > {
	private final HashMap<Long, T> storage = new HashMap<>();
	private long counter = 0L;

	public T create(final T data) {
		validate(data);
		data.setId(++counter);
		storage.put(data.getId(), data);
		return data;
	}
...
}

2023-07-08 09:21 UTC, VadimZharkov commented on src/test/java/ru/yandex/practicum/filmorate/UserControllerTest.java
> +    @SneakyThrows
мне в двух словах не объяснить) вот ссылка на доку
https://projectlombok.org/features/SneakyThrows

просто это уже выше джуновского уровня

2023-07-08 09:22 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/controller/Controller.java
> +public abstract class Controller<T> {
В переписке отписался как можно сделать

2023-07-08 09:24 UTC, VadimZharkov requested changes
Нужно еще немного доработать

2023-07-09 05:00 UTC, VadimZharkov approved these changes

2023-07-11 18:02 UTC, merged